### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by Worryinglamb08** [DarkNosS96/WightDisplay-for-trew_hud_ui-FiveM#1]
![2020-01-08_21h55_19](https://user-images.githubusercontent.com/58918753/72006945-b817b780-3261-11ea-83c0-931c2a5d5676.png)
 Guide me please

**Comment by DarkNosS96-zz** [comment]
are you using the es_extended with weight system?

**Comment by Worryinglamb08** [comment]
Yes I am
