### ISSUE TITLE
Status Bar not moving

### ISSUE THREAD

**Issue by Berkeratay** [DarkNosS96/WightDisplay-for-trew_hud_ui-FiveM#2]
I am using this with new ESX and inventoryhud.
Any ideas what might be the problem

**Comment by DarkNosS96-zz** [comment]
what is the problem? any errors?

**Comment by Berkeratay** [comment]
On the last commit.
Line 9
TriggerEvent('esx:getShvnsbla2aredObjvnsbla2ect', function(obj) ESX = obj end)

I suppose it should be
TriggerEvent('esx:getSharedobject', function(obj) ESX = obj end)

My weight limit is double from es_extended config.lua "50" and all market items on inventoryhud is weight 1.

Maxweight 25000 does not really respond when i buy or consume items.
I tried 50.

Spawn starts full icon.
When you consume something it goes down.
When you buy something it goes up.
But even that does not seem like correct calculation.

**Comment by DarkNosS96-zz** [comment]
try the latest version, i updated the spawn problem
if your max weight limit is 50, try 50000

**Comment by Berkeratay** [comment]
Thanks Dark i saw the updates.
For some reason after many attempts it started working with only one exception.
Max Weight i put 50! 25000 or 50000 literally does not visualize anything.
Might be my Dbase. Might be the latest ESX.

**Comment by DarkNosS96-zz** [comment]
im not using the latest version, so i dont know if you must change it to 50 or 50000
i believe the new es_extended change it to kilos and not in grams, so when you change it to 50000 it changes a bit (maybe a pixel) cuz the max weight is 1000 times bigger :P

**Comment by JoluBGame** [comment]
I have the same problem, I use the new ESX, and the icon always appears blank.

**Comment by Berkeratay** [comment]
Set weight to 25.
Actually check your es extended config whatever is the max weight set it to that. He did grams i think new esx use kilos now.

**Comment by JoluBGame** [comment]
I use the weight at 70 and set it to 70 but it's still the same

**Comment by Berkeratay** [comment]
Make sure you got the latest version he updated it 2 days ago

**Comment by Berkeratay** [comment]
This is solved by weight adjustment.
Thanks
